# Generated by Django 5.2.6 on 2025-10-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discounted_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
