# Generated by Django 5.2.6 on 2025-10-07 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_course_category_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='course',
            name='review_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
