# Generated by Django 5.2.6 on 2025-10-07 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_lesson_count_course_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='parent_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_courses', to='course.course'),
        ),
    ]
