# Generated by Django 5.2.6 on 2025-10-07 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_course_parent_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='parent_course',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='course.category'),
        ),
    ]
