# Generated by Django 5.2.6 on 2025-10-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_course_parent_course_category_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_sliders',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
