# Generated by Django 5.2.6 on 2025-10-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_course_featured_sliders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='featured_sliders',
        ),
        migrations.AddField(
            model_name='course',
            name='featured_in_sliders',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/courses/featured-images'),
        ),
        migrations.AlterField(
            model_name='course',
            name='featured_video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
