# Generated by Django 5.2.6 on 2025-10-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_course_featured_sliders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='featured_in_sliders',
        ),
    ]
