# Generated by Django 5.2.6 on 2025-10-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_remove_course_featured_in_sliders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(related_name='course_category', to='course.category'),
        ),
    ]
