# Generated by Django 5.2.6 on 2025-10-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
