# Generated by Django 5.2.6 on 2025-10-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_course_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
