# Generated by Django 5.2.6 on 2025-10-24 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_courselesson_coursevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lessons', to='course.course'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_videos', to='course.course'),
        ),
    ]
