# Generated by Django 5.2.6 on 2025-10-24 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_alter_courselesson_course_alter_coursevideo_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_videos', to='course.courselesson'),
        ),
    ]
