# Generated by Django 5.2.6 on 2025-10-24 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_author_author_rating_author_author_reviews_and_more'),
        ('course', '0023_alter_coursevideo_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_author', to='accounts.author'),
        ),
    ]
