# Generated by Django 5.2.6 on 2025-10-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_enrolledcourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledcourse',
            old_name='date',
            new_name='enrolled_at',
        ),
    ]
