# Generated by Django 5.2.6 on 2025-11-02 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='enrolled_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.enrolledcourse'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
