# Generated by Django 5.2.6 on 2025-11-02 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_alter_payment_enrolled_course_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='enrolled_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.enrolledcourse'),
        ),
    ]
