# Generated by Django 5.2.6 on 2025-11-05 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_alter_payment_enrolled_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_course', to='course.course'),
        ),
    ]
