# Generated by Django 5.2.6 on 2025-10-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField()),
                ('about_author', models.CharField(max_length=100, null=True)),
                ('author_profile', models.ImageField(upload_to='uploads/author')),
            ],
        ),
    ]
