# Generated by Django 5.2.6 on 2025-10-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='author_reviews',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='author_role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='author_students',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='about_author',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
