# Generated by Django 5.2.6 on 2025-10-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_author_author_rating_author_author_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about_author',
            field=models.TextField(null=True),
        ),
    ]
