# Generated by Django 5.2.6 on 2025-10-24 16:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_author_about_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about_author',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
