# Generated by Django 5.2.6 on 2025-10-07 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_remove_course_featured_in_sliders'),
        ('home', '0002_slider_slider_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_slider', to='course.course'),
        ),
    ]
